# Creating array

In [1]:
from sys import getsizeof
import numpy as np
import matplotlib.pyplot as plt

# using list or tuple
print([1, 2, 3], np.array([1, 2, 3]))
print((1, 2, 3), np.array((1, 2, 3)))

[1, 2, 3] [1 2 3]
(1, 2, 3) [1 2 3]


In [6]:
# does not work with multiple numeric arguments
a = np.array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [7]:
# milti-level list -> multi-dimensional array
print([[1, 2, 3], [4, 5, 6]])
print(np.array([[1, 2, 3], [4, 5, 6]]))

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [8]:
# convert back to list
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.tolist())
print(list(a))

[[1, 2, 3], [4, 5, 6]]
[array([1, 2, 3]), array([4, 5, 6])]


In [9]:
# using arange
print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(2, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [10]:
# using linspace() to generate evenly spaced numbers
print(np.linspace(0, 10, 6))
print(np.linspace(0, 100, 11))

[ 0.  2.  4.  6.  8. 10.]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [11]:
np.sin(np.linspace( 0, 2*np.pi, 51 ) )

array([ 0.00000000e+00,  1.25333234e-01,  2.48689887e-01,  3.68124553e-01,
        4.81753674e-01,  5.87785252e-01,  6.84547106e-01,  7.70513243e-01,
        8.44327926e-01,  9.04827052e-01,  9.51056516e-01,  9.82287251e-01,
        9.98026728e-01,  9.98026728e-01,  9.82287251e-01,  9.51056516e-01,
        9.04827052e-01,  8.44327926e-01,  7.70513243e-01,  6.84547106e-01,
        5.87785252e-01,  4.81753674e-01,  3.68124553e-01,  2.48689887e-01,
        1.25333234e-01, -3.21624530e-16, -1.25333234e-01, -2.48689887e-01,
       -3.68124553e-01, -4.81753674e-01, -5.87785252e-01, -6.84547106e-01,
       -7.70513243e-01, -8.44327926e-01, -9.04827052e-01, -9.51056516e-01,
       -9.82287251e-01, -9.98026728e-01, -9.98026728e-01, -9.82287251e-01,
       -9.51056516e-01, -9.04827052e-01, -8.44327926e-01, -7.70513243e-01,
       -6.84547106e-01, -5.87785252e-01, -4.81753674e-01, -3.68124553e-01,
       -2.48689887e-01, -1.25333234e-01, -2.44929360e-16])

In [14]:
# create uniform array
print(np.ones([3, 4]), '\n')
print(np.zeros([3, 4]), '\n')
print(np.empty([3, 4]), '\n')
print(np.full([3, 4], 'hello'), '\n')

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']] 



In [15]:
# create uniform array based on the shape of another array
print(np.ones_like(np.zeros([3, 4])))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Data types

In [16]:
print(np.dtype(int))
print(np.dtype(float)) # takes up large storage when saving data in default types

int32
float64


In [17]:
# you can specify the date you want when creating a new array
print(np.ones([3, 4], dtype=int), '\n')
print(np.ones([3, 4], dtype=str), '\n')
print(np.zeros([3, 4], dtype=int), '\n')
print(np.zeros([3, 4], dtype=str), '\n')
print(np.empty([3, 4], dtype=int), '\n')
print(np.empty([3, 4], dtype=str), '\n')

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']] 



In [21]:
# be careful about the range of a data type
print(np.power(100, 8, dtype=np.int64))
print(np.power(100, 8, dtype=np.int32))
print(np.power(100, 8, dtype=np.int16))

10000000000000000
1874919424
0


In [22]:
# check the range
print(np.iinfo(np.int64))
print(np.iinfo(np.int32))
print(np.iinfo(np.int16))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------



In [23]:
# structured array is very powerful to deal with table-like data (but we will learn about a more powerful tool very soon)
dtype = np.dtype([('siteno', 'U10'), ('datetime', 'M'), ('streamflow', 'f2')])
print(dtype)

[('siteno', '<U10'), ('datetime', '<M8'), ('streamflow', '<f2')]


# Indexing

In [ ]:
# first of all array is mutable; the index is referencing to the location of the data (referencing)
a = np.ones_like(np.zeros([3, 4]))
print('before', a[1, 1])
a[1, 1] = 2
print('after', a[1, 1])

In [ ]:
# 1. indexing like lists
#a1 = np.random.randint(1, 100, 10)
a1 = np.arange(10)
print(a1)
print(a1[:5])
print(a1[7:])
print(a1[-5:])

In [ ]:
# specify the step
print(a1[:8:2])

In [ ]:
# 2. numpy feature indexing by list/array of specific indices
print(a1[[2, 3, 6, 9]])

In [ ]:
# 2.2 what is returned when index arrays are used is an array with the same shape as the index array
print(a1)
print(a1[np.array([[2, 3], [-2, -1]])])

In [ ]:
# numpy feature indexing by boolean
temperatures = [-5.4, 1.0, -1.3, -4.8, 3.9, 0.1, -4.4, 4.0, -2.2, -3.9, 4.4,
                -2.5, -4.6, 5.1, 2.1, -2.4, 1.9, -3.3, -4.8, 1.0, -0.8, -2.8,
                -0.1, -4.7, -5.6, 2.6, -2.7, -4.6, 3.4, -0.4, -0.9, 3.1, 2.4,
                1.6, 4.2, 3.5, 2.6, 3.1, 2.2, 1.8, 3.3, 1.6, 1.5, 4.7, 4.0,
                3.6, 4.9, 4.8, 5.3, 5.6, 4.1, 3.7, 7.6, 6.9, 5.1, 6.4, 3.8,
                4.0, 8.6, 4.1, 1.4, 8.9, 3.0, 1.6, 8.5, 4.7, 6.6, 8.1, 4.5,
                4.8, 11.3, 4.7, 5.2, 11.5, 6.2, 2.9, 4.3, 2.8, 2.8, 6.3, 2.6,
                -0.0, 7.3, 3.4, 4.7, 9.3, 6.4, 5.4, 7.6, 5.2]
temp = np.array(temperatures)

temp1 = temp[temp < -2]
temp2 = temp[(temp >= -2) & (temp < 2)]
temp3 = temp[(temp >= 2)  & (temp < 15)]

print(temp1.mean())
print(temp2.mean())
print(temp3.mean())

In [ ]:
# Numpy broadcasting
temp = np.tile(temperatures, 3).reshape([3, -1])
lower = np.array([-np.inf, -2, 2]).reshape([3, 1])
upper = np.array([-2, 2, 15]).reshape([3, 1])
 
temp = np.where((temp > lower) & (temp <= upper), temp, np.nan )
temp

In [ ]:
np.nanmean(temp, axis=1)

In [ ]:
def method1(temperatures):
    temp = np.array(temperatures)
    temp1 = temp[temp < -2]
    temp2 = temp[(temp >= -2) & (temp < 2)]
    temp3 = temp[(temp >= 2)  & (temp < 15)]

    return temp1.mean(), temp2.mean(), temp3.mean()

def method2(temperatures):
    temp = np.tile(temperatures, 3).reshape([3, len(temperatures)])
    lower = np.array([-np.inf, -2, 2]).reshape([3, 1])
    upper = np.array([-2, 2, 15]).reshape([3, 1])

    temp = np.where((temp > lower) & (temp <= upper), temp, np.nan )
    return(np.nanmean(temp, axis=1))

%timeit method1(temperatures)
%timeit method2(temperatures)

In [ ]:
# boolean indexing returns a 1-D array containing all the elements in the indexed array 
# corresponding to all the true elements in the boolean array
a1 = np.arange(6).reshape([2, 3])
b  = np.array(
        [[True, False, False],
         [False, True, True]])
print(a1[b])

In [ ]:
# unless the array has more dimension than the index array
a2 = a1.reshape([3, 2])
b = np.array([True, False, True])
a2[b]

In [ ]:
# combining the indexing method
a1 = np.arange(16).reshape([4,4])
print(a1)
print(a1[:2, [1, 3]])


In [ ]:
# assignment
a = np.arange(10)
print(a)

In [ ]:
a[:] = 1
print(a)

In [ ]:
# change to another object
a = 1
print(a)

# Change shape/dimension

In [ ]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print('shape is', a.shape)

In [ ]:
print(a.flatten())
print(a.reshape(4, 3))
print(a.reshape(6, 2))

In [ ]:
# transposed
a.T

In [ ]:
# stacking
a = [1, 2, 3]
b = [3, 5, 6]

print(np.vstack([a, b]))
print(np.hstack([a, b]))
print(np.concatenate([a, b]))

In [ ]:
a = np.array(a).reshape(1, 3)
b = np.array(b).reshape(1, 3)
print(np.concatenate([a, b], axis=0))


# Armetic operationb

In [ ]:
a = np.array([2, 2, 2, 2])
b = np.array([1, 2, 4, 8])


print('a:', a)
print('b:', b)

print('+:', b + a)
print('-:', b - a)
print('*:', b * a)
print('/:', b / a)
print('%:', b % a)
print('@:', b @ a)      # Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. 
print('dot:', b.dot(a)) # The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [ ]:
print('b2:', b ** 2)
print('b2:', b ** 0.5)

In [ ]:
# += and *=, act in place to modify an existing array
print(a)
a += 1
print(a)

In [ ]:
# unary operations
print(b.sum())
print(b.min())
print(b.max())

In [ ]:
# for multidimensional
b = np.arange(12).reshape(3,4)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

# Common Numpy functions

```
all, any, apply_along_axis, 
argmax, argmin, argsort, average, bincount, ceil, 
clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, 
max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, 
round, sort, std, sum, trace, transpose, var, vdot, vectorize, where
```

In [ ]:
# clip values
a = np.array([3, 8, 7, 5, 4])
np.clip(a, 4, 6)

In [ ]:
# cumsum
a.cumsum()

In [ ]:
# difference
a = a.cumsum()
print(np.diff(a))
print(np.diff(a, 2))

In [ ]:
# where to replace
a = np.array([8, 3, 5, 7, 9])
np.where(a > 5, a, np.nan)

In [ ]:
b = np.where(a > 5, a, np.nan)
b.sum()

In [ ]:
# exclude np.nan
np.nansum(b)

In [ ]:
# repeat and tile
a = np.arange(3)
print(np.repeat(a, 4))
print(np.tile(a, 4))

In [ ]:
# argmax, argmin, argsort nonzero returns the result of index, 
# very helpful when you need to based on an array's value to located an element in another array

# find the precip on different land cover types
landcover     = np.random.randint(1, 5, [5, 5])
precipitation = np.random.random([5, 5])

print('landuse\n', landcover)
print('landuse\n', precipitation)

# plot


# find location of irrigated land


# identify the precipitation on these cells and calculate the mean



# identify the wetest and driest land cover and their mean precipitation

In [ ]:
np.clip


In [ ]:
# How to get the common items between two python numpy arrays?
a = [1, 3, 5, 7, 9]
b = [2, 3, 4, 5, 6]
np.intersect1d(a, b)

In [ ]:
# Other useful function

# calculate histogram/freq
mu, sigma = 2, 0.5
v = np.random.normal(mu,sigma,10000)
(n, bins) = np.histogram(v, bins=50, density=True)
plt.plot(.5*(bins[1:]+bins[:-1]), n)